allowBuilds:
  esbuild: true
  ffmpeg-static: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@remotion/bundler@4.0.533'
  - '@remotion/captions@4.0.533'
  - '@remotion/cli@4.0.533'
  - '@remotion/codemods@4.0.533'
  - '@remotion/compositor-darwin-arm64@4.0.533'
  - '@remotion/compositor-darwin-x64@4.0.533'
  - '@remotion/compositor-linux-arm64-gnu@4.0.533'
  - '@remotion/compositor-linux-arm64-musl@4.0.533'
  - '@remotion/compositor-linux-x64-gnu@4.0.533'
  - '@remotion/compositor-linux-x64-musl@4.0.533'
  - '@remotion/compositor-win32-x64-msvc@4.0.533'
  - '@remotion/elevenlabs@4.0.533'
  - '@remotion/licensing@4.0.533'
  - '@remotion/media-parser@4.0.533'
  - '@remotion/media-utils@4.0.533'
  - '@remotion/media@4.0.533'
  - '@remotion/openai-whisper@4.0.533'
  - '@remotion/paths@4.0.533'
  - '@remotion/player@4.0.533'
  - '@remotion/renderer@4.0.533'
  - '@remotion/sdk@4.0.533'
  - '@remotion/streaming@4.0.533'
  - '@remotion/studio-protocol@4.0.533'
  - '@remotion/studio-server@4.0.533'
  - '@remotion/studio-shared@4.0.533'
  - '@remotion/studio@4.0.533'
  - '@remotion/timeline-utils@4.0.533'
  - '@remotion/web-renderer@4.0.533'
  - '@remotion/zod-types@4.0.533'
  - remotion@4.0.533
  - '@remotion/animated-emoji@4.0.533'
  - '@remotion/animation-utils@4.0.533'
  - '@remotion/cloudrun@4.0.533'
  - '@remotion/effects@4.0.533'
  - '@remotion/enable-scss@4.0.533'
  - '@remotion/fonts@4.0.533'
  - '@remotion/gif@4.0.533'
  - '@remotion/google-fonts@4.0.533'
  - '@remotion/gsap@4.0.533'
  - '@remotion/install-whisper-cpp@4.0.533'
  - '@remotion/lambda-client@4.0.533'
  - '@remotion/lambda@4.0.533'
  - '@remotion/layout-utils@4.0.533'
  - '@remotion/light-leaks@4.0.533'
  - '@remotion/lottie@4.0.533'
  - '@remotion/mac-cursors@4.0.533'
  - '@remotion/mcp@4.0.533'
  - '@remotion/motion-blur@4.0.533'
  - '@remotion/noise@4.0.533'
  - '@remotion/preload@4.0.533'
  - '@remotion/rive@4.0.533'
  - '@remotion/rough-notation@4.0.533'
  - '@remotion/rounded-text-box@4.0.533'
  - '@remotion/serverless-client@4.0.533'
  - '@remotion/serverless@4.0.533'
  - '@remotion/sfx@4.0.533'
  - '@remotion/shapes@4.0.533'
  - '@remotion/skia@4.0.533'
  - '@remotion/starburst@4.0.533'
  - '@remotion/tailwind-v4@4.0.533'
  - '@remotion/tailwind@4.0.533'
  - '@remotion/three@4.0.533'
  - '@remotion/transitions@4.0.533'
  - '@remotion/vercel@4.0.533'
  - '@remotion/video-matting@4.0.533'
  - '@remotion/webcodecs@4.0.533'
  - '@remotion/whisper-web@4.0.533'
  - '@remotion/whisper-webgpu@4.0.533'
  - '@remotion/zod-types-v3@4.0.533'
